#include <windows.h>
#include <iostream>
#include <stdio.h>
#include "XWnd.h"
#include "XArticle.h"
#include "XArticleTag.h"
//#include "Debug.h"
//#include "resource.h"
//#include "CDialog.h"
//#include "CFindDlg.h"
#include "SeqStack.h"
#include "RedoUndo.h"
#include "XEdit.h"